[package]
name = "fasta"
version = "0.1.0"
authors = ["Paul Magwene <paul.magwene@duke.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"